CREATE TABLE ARTICLE_COUNT_TB2
(
    ARTICLE_ID NUMBER(10)
);
ALTER TABLE ARTICLE_COUNT_TB2 ADD FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLE_TB(ARTICLE_ID)
CREATE TABLE ARTICLE_COUNT_TB2 
(
    ARTICLE_ID NUMBER(10) 
    ,READ_COUNT NUMBER(6) DEFAULT 0
);

SELECT ARTICLE_ID, READ_COUNT 
FROM ARTICLE_COUNT_TB2 
ORDER BY READ_COUNT DESC

SELECT ARTICLE_ID FROM ARTICLE_COUNT_TB 
WHERE 1 = 1
GROUP BY ARTICLE_ID 
ORDER BY COUNT(ARTICLE_ID) DESC

SELECT ARTICLE_ID, COUNT(ARTICLE_ID) FROM ARTICLE_COUNT_TB 
GROUP BY ARTICLE_ID

SELECT ARTICLE_ID, RANK() OVER(ORDER BY READ_COUNT)
FROM ARTICLE_COUNT_TB2

DROP TABLE ARTICLE_COUNT_TB
INSERT INTO ARTICLE_COUNT_TB  VALUES (10012);
INSERT INTO ARTICLE_COUNT_TB2(  READ_COUNT , ARTICLE_ID ) VALUES (27,'10004')
INSERT INTO ARTICLE_COUNT_TB2(  READ_COUNT , ARTICLE_ID ) VALUES (21,'10023')
INSERT INTO ARTICLE_COUNT_TB2 ( READ_COUNT , ARTICLE_ID ) VALUES (18,'10027')
INSERT INTO ARTICLE_COUNT_TB2(  READ_COUNT , ARTICLE_ID ) VALUES (15,'10018')
INSERT INTO ARTICLE_COUNT_TB2 ( READ_COUNT , ARTICLE_ID ) VALUES (5,'10033')