SELECT * FROM NOTICE_TB

CREATE TABLE NOTICE_TB(
	NOTICE_ID NUMBER(10) PRIMARY KEY
	,ARTICLE_ID NUMBER(10) NOT NULL
	,DISPLAY_START_DATE DATE NOT NULL
	,DISPLAY_END_DATE DATE NOT NULL
	,CONSTRAINT NOTICE_ARTICLE_FK FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLE_TB(ARTICLE_ID)
)
 ALTER TABLE ARTICLE MODIFY (MODIFY_DATE DEFAULT null);

CREATE SEQUENCE NOTICE_ID_SEQ
 	   START WITH 10001
   	   INCREMENT BY 1
	   MAXVALUE 99999
       MINVALUE 10001
       NOCYCLE;
SELECT NOTICE_ID_SEQ.NEXTVAL FROM DUAL
INSERT INTO NOTICE_ARTICLE
VALUES
(
	10006
	,10072
	,'2017-07-25'
	,'2017-07-28'
)

SELECT  NVL(MIN('Y'), 'N')
FROM 	DUAL
WHERE	1			= 1
AND		EXISTS
		(
			SELECT 
					1
			FROM	NOTICE_ARTICLE
			WHERE	
					ARTICLE_ID = '10087'
				)
ALTER TABLE ARTICLE ADD CONSTRAINT NOTICE_ARTICLE_FK FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLE(ARTICLE_ID)
DROP TABLE ARTICLE_REPLY
delete from NOTICE_ARTICLE
SELECT * FROM NOTICE_ARTICLE
ALTER TABLE NOTICE_ARTICLE DROP CONSTRAINT NOTICE_ARTICLE_PKEY;
CONSTRAINT FK_ID01 FOREIGN KEY(WRITE_MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
ALTER TABLE NOTICE_ARTICLE_FK ADD CONSTRAINT NOTICE_ARTICLE_FK FOREIGN KEY(NOTICE_ID_NO) REFERENCES ARTICLE(ARTICLE_ID);
ALTER TABLE NOTICE_ARTICLE RENAME COLUMN EXPIRATION_DATE TO DISPLAY_END_DATE;


  START WITH 
  A.ARTICLE_ID IN ( SELECT ARTICLE_ID FROM ARTICLE_TB WHERE A.WRITE_MEMBER_ID = 'admin')

  CONNECT BY  A.ARTICLE_ID = PRIOR A.PARENT_ID
  ORDER SIBLINGS BY
                ARTICLE_ID DESC



